#!/usr/bin/env python3
import sys, os, os.path

def encoder(pscode):
    text = open(pscode).read()
    out = open(pscode[:pscode.index(".")] + ".bin", "w")
    if text == '':
        out.write('')
        return None
    txt = ""
    for i in text:
        txt += (bin(ord(i))[2:]+ ' ')
    out.write(txt[:-1])
    out.close()

if not len(sys.argv) == 2:
        print('usage: pscode FILE')
        sys.exit(0)
if not '.p' == sys.argv[-1][-2:]:
        print('Killed: 9')
        sys.exit(0)
if not os.path.exists(sys.argv[-1]):
        print('No such file or directory')
        sys.exit(0)
        
encoder(sys.argv[-1])
os.system('~/proton/proton -r ' + sys.argv[-1][:sys.argv[-1].index('.')]+'.bin')
os.system('rm ' + sys.argv[-1][:sys.argv[-1].index('.')]+'.bin')
