#!/usr/bin/env python3
import sys, os, os.path

def encoder(pscode):
    text = open(pscode).read()
    out = open(pscode[:pscode.index(".")] + ".bin", "w")
    if text == '':
        out.write('')
        return None
    txt = ""
    for i in text:
        txt += (bin(ord(i))[2:]+ ' ')
    out.write(txt[:-1])
    out.close()

if not len(sys.argv) == 2:
        print('usage: pscode FILE')
        sys.exit(0)
if not '.p' == sys.argv[-1][-2:]:
        print('Killed: 9')
        sys.exit(0)
if not os.path.exists(sys.argv[-1]):
        print('No such file or directory')
        sys.exit(0)
        
encoder(sys.argv[-1])

def decoder(pscode):
    binary = open(pscode).read()
    out = open(pscode[:pscode.index(".")] + ".p", "w")
    if binary == '':
        out.write('')
        os.system('rm '+pscode)
        return None
    binary = binary.split(" ")
    text = ""
    for i in binary:
        text += chr(int(i, base=2))
    out.write(text)
    out.close()
    os.system('rm '+pscode)
    
def code(filename):
    argrem = filename
    time.sleep(1)
    import os
    import os.path
    if (os.path.exists(filename)):
        if '.' in filename:
            time.sleep(0)
        else:
            print("\n(1/3) Loading Program File ..... [ "+R+"FAIL"+E+" ]\n")
            import sys
            sys.exit()
            
        if (argrem[-(argrem[::-1].index('.')):]) == 'bin':
            print("\n(1/3) Loading Program File  ..... [ "+G+"OK"+E+" ]")
            
        else:
            print("\n(1/3) Loading Program File ..... [ "+R+"FAIL"+E+" ]\n")
            import sys
            sys.exit()
    else:
        print("\n(1/3) Loading Program File ..... [ "+R+"FAIL"+E+" ]\n")
        import sys
        sys.exit()
        
    if (os.path.exists("/data/data/com.termux")):
        pspath = "/data/data/com.termux/files/usr/bin/pscript"
    else:
        pspath = "/usr/local/bin/pscript"
        
    time.sleep(1)
            
    if (os.path.exists(pspath)):
        print("(2/3) Loading ProtonScript  ..... [ "+G+"OK"+E+" ]")
    else:
        print("(2/3) Loading ProtonScript ..... [ "+R+"FAIL"+E+" ]\n")
        import sys
        sys.exit()
    
    print("(3/3) Running Program File  ..... [ "+G+"OK"+E+" ]")
    time.sleep(2)
    decoder(filename)
    
code(sys.argv[-1])
