#!/usr/bin/env python3

# 
#            --------------------------------------------------
#                               ProtonScript               
#            --------------------------------------------------
#          Copyright (C) <2015>  <Entynetproject (Ivan Nikolsky)>
#
#        This program is free software: you can redistribute it and/or modify
#        it under the terms of the GNU General Public License as published by
#        the Free Software Foundation, either version 3 of the License, or
#        any later version.
#
#        This program is distributed in the hope that it will be useful,
#        but WITHOUT ANY WARRANTY; without even the implied warranty of
#        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#        GNU General Public License for more details.
#
#        You should have received a copy of the GNU General Public License
#        along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#    About Author :   
#    Founder   : Entynetproject (Ivan Nikolsky)
#    Site      : http://entynetproject.simplesite.com/
#    Instagram : @entynetproject 
#    Twitter   : @entynetproject
#    Email     : entynetproject@gmail.com
#

import sys, os, os.path

def encoder(pscode):
    text = open(pscode).read()
    out = open(pscode[:pscode.index(".")] + ".psc", "w")
    if text == '':
        out.write('')
        return None
    txt = ""
    for i in text:
        txt += (bin(ord(i))[2:]+ ' ')
    out.write(txt[:-1])
    out.close()

if not len(sys.argv) == 2:
        print('usage: psenv FILE')
        sys.exit(0)
if not '.p' == sys.argv[-1][-2:]:
        REDL="\033[1;31m"
        WHSL="\033[0;97m"
        ENDL="\033[0m"
        print(REDL+"[-]"+ENDL+" "+WHSL+"ProtonScript program file is not executable!"+ENDL)
        sys.exit()
if not os.path.exists(sys.argv[-1]):
        REDL="\033[1;31m"
        WHSL="\033[0;97m"
        ENDL="\033[0m"
        print(REDL+"[-]"+ENDL+" "+WHSL+"No such ProtonScript program file!"+ENDL)
        sys.exit()
        
encoder(sys.argv[-1])
pwd = os.getcwd()
os.system('cd ~/proton && chmod +x proton && ./proton -r ' + pwd + '/' + sys.argv[-1][:sys.argv[-1].index('.')]+'.psc')
os.system('rm ' + sys.argv[-1][:sys.argv[-1].index('.')]+'.psc')
